INSERT INTO USERS(ID,NAME,SURNAME,EMAIL,PASSWORD,ROLE_NAME)VALUES (1,'aa','bb','aa@aa.com',1234,'ROLE_USER');
INSERT INTO USERS(ID,NAME,SURNAME,EMAIL,PASSWORD,ROLE_NAME)VALUES (2,'cc','dd','cc@cc.com',1234,'ROLE_USER');
